name: CPPCheck-annotations
description: Automatically checks pull requests changes with cppcheck and prints the results as GitHub annotations
author: p-ranav
branding:
  icon: alert-circle
  color: green
inputs:
  hash:
    description: 'Hash of the Pull request commit'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.hash }}
