name: CPPCheck-annotations
description: Automatically checks pull requests changes with cppcheck and prints the results as GitHub annotations
author: p-ranav
branding:
  icon: alert-circle
  color: green
inputs:
  path:
    description: 'Project Directory'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
